view_sampler:
  name: fps
  num_context_views: 8
  num_target_views: 12

name: thuman
roots: [datasets/THuman2_0_render]

image_shape: 512
cameras_are_circular: false
overfit_to_scene: null

near: 0.1
far: 4.0
scene_scale_factor: 2.1
background_color: [0.0, 0.0, 0.0]

random_view: true
num_views: 16
time_range: 1
norm_extrinsic: true
norm_sampled_views: true

train_times_per_scene: 1
shuffle_val: false
max_val_batches: -1

num_training_scenes: -1
num_val_scenes: -1
start_scene_training: 0
start_scene_val: 0

